version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_URL=sqlite3:/app/db/development.sqlite3
    volumes:
      - ./backend:/app
      - backend_bundle:/usr/local/bundle
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  backend_bundle:

networks:
  app-network:
    driver: bridge 